CC := gcc

fopen: fopen.cpp
#gcc -o fopen fopen.cpp
	-$(CC) -o $@ $^
#./fopen
	-./$@
#rm ./fopen
	-rm ./$@

fclose: fclose.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputc: fputc.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputs: fputs.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fprintf: fprintf.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgetc: fgetc.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@
	

fscanf: fscanf.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

stdin_out_err: stdin_out_err.cpp
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@